#!/bin/bash
mkdir -p /unreal/miniconda3
TMP=$(mktemp -d)
cd $TMP
#mkdir -p /unreal/miniconda3
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash $TMP/Miniconda3-latest-Linux-x86_64.sh -b -f -p /unreal/miniconda3 
/unreal/miniconda3/bin/conda init
/unreal/miniconda3/bin/conda config --set auto_activate_base false
rm -Rf $TMP
