# Ansible playbook for SPF13
#
# Author: Josh Cox <josh 'at' webhosting coop>
---

- name: nodejs install
  become: True
  hosts: thalhalla

  tasks:
  - name: Installing latest nodejs
    script: nodelatest.sh
  - name: Installing nodejs-devl
    script: npmModInstaller.sh
