# Ansible playbook for SPF13
#
# Author: Josh Cox <josh 'at' webhosting coop>
---

- name: nodejs install
  hosts: thalhalla

  tasks:
  - name: Installing nodejs
    script: nodelatest.sh
  - name: Installing nodejs mods
    script: npmModInstaller.sh
