# Ansible playbook for SPF13
#
# Author: Josh Cox <josh 'at' webhosting coop>
---

- name: nodejs install
  hosts: thalhalla

  tasks:
  - script: nodelatest.sh
  - name: Installing nodejs-devl
    become: True
  - script: npmModInstaller.sh
