#!/bin/bash
#set -eux
set -eu

sorter () {
  unsorted=$1
  sort $unsorted |uniq> $unsorted.sorted
  #mv -v $unsorted.sorted $unsorted
  mv $unsorted.sorted $unsorted
}
sorter pacman_list
sorter bauerbill_list
