# Ansible playbook for thalhalla
#
# Author: Josh Cox <josh 'at' webhosting coop>
---

- name: Bootstrapping developer environment
  hosts: all
  vars:
     NAME_contents: "{{ lookup('file', 'NAME') }}"
     USERNAME_contents: "{{ lookup('file', 'USERNAME') }}"

  tasks:

  - name: Determining username
    shell:  whoami
    register: whoami
    sudo: False

  - name: apt-get update and upgrade.
    sudo: True
    apt:  upgrade=yes update_cache=yes

  - name: Installing zsh, vim, git, tmux, etc.
    sudo: True
    apt:  name={{ item  }} state=latest
    with_items:
    - zsh
    - vim-gtk
    - git
    - byobu
    - kdiff3
    - htop
    - curl
    - wget 
    - build-essential
    - synergy
    - exuberant-ctags

  - name: Changing the default shell to zsh
    sudo: True
    user:  shell=/bin/zsh name={{ USERNAME_contents }}

- name: Entering Plugin Nirvana
  hosts: all
  sudo: False

  tasks:

  - name: Backing up existing ~/.zshrc
    script: backupexistingzsh.sh  creates=/home/root/backupzshbootstrapped.txt

  - name: Installing oh-my-zsh (https://github.com/robbyrussell/oh-my-zsh)
    git:  repo=https://github.com/robbyrussell/oh-my-zsh dest=~/.oh-my-zsh

  - name: Creating new ~/.zshrc
    script: installohmyzshtemplate.sh  creates=/home/root/ohmyzshbootstrapped.txt

  - name: Installing spf13-vim, The Ultimate Vim Distribution (http://vim.spf13.com)
    script: installspf13vim.sh  creates=/home/root/vimspf13bootstrapped.txt
