# Ansible playbook for thalhalla
#
# Author: Josh Cox <josh 'at' webhosting coop>
---

- name: Bootstrapping developer environment
  hosts: thalhalla
  vars:
    NAME_contents: "{{ lookup('file', 'NAME') }}"
    USERNAME_contents: "{{ lookup('file', 'USERNAME') }}"

  tasks:

  - name: Installing zsh, vim, git, tmux, etc.
    sudo: True
    apt:  name={{ item  }} state=latest
    with_items:
    - zsh
    - vim-athena
    - git
    - byobu
    - kdiff3
    - htop
    - curl
    - wget
    - keychain
    - awesome
    - awesome-extra
    - build-essential
    - synergy
    - exuberant-ctags
    - nload
    - iftop
    - iptraf
    - nethogs
    - bmon
    - slurm
    - tcptrack
    - vnstat
    - bwm-ng
    - cbm
    - speedometer
    - netdiag
    - ifstat
    - dstat
    - collectl
    - nmap
    - sshfs
    - ack-grep
    - net-tools
    - dnsutils
    - tilda
    - chromium
    - iceweasel
    - icedove
    - lynx-cur
    - links2
    - w3m
    - w3m-img
    - irssi
    - mutt
    - tree
    - ssh-askpass-gnome
    - autokey



  - name: Changing the default shell to zsh
    sudo: True
    user:  shell=/bin/zsh name={{ USERNAME_contents }}
  - script: bootstrapThoth.sh
