# Ansible playbook for thalhalla
#
# Author: Josh Cox <josh 'at' webhosting coop>
---

- name: update developer environment
  hosts: thalhalla
  tasks:
  - name: apt-get update and upgrade.
    become: True
    apt:  upgrade=yes update_cache=yes cache_valid_time=7200
