# Ansible playbook for thalhalla video (includes all graphics arts [ie anything visual])
#
# Author: Josh Cox <josh 'at' webhosting coop>
---

- name: Bootstrapping video developer environment
  hosts: thalhalla
  vars:
    NAME_contents: "{{ lookup('file', 'NAME') }}"
    USERNAME_contents: "{{ lookup('file', 'USERNAME') }}"

  tasks:

  - name: Installing blender, gimp, inkcsape, etc.
    become: True
    pacman:  name={{ item  }} state=latest
    with_items:
    - blender
    - inkscape
    - gimp
    - xsane
    - hugin
    - kdenlive
